# Generated by Django 4.2.2 on 2023-06-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrutaSecaDelivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entregable',
            new_name='Envios',
        ),
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='MiCuenta',
        ),
        migrations.RenameModel(
            old_name='Profesor',
            new_name='MisPedidos',
        ),
        migrations.RenameModel(
            old_name='Curso',
            new_name='Producto',
        ),
    ]
